const WATCH_GET_EXPENSE_DATA = 'WATCH_GET_EXPENSE_DATA';
const WATCH_UPLOAD_STATEMENT = 'WATCH_UPLOAD_STATEMENT';
const WATCH_LOGIN_USER = 'WATCH_LOGIN_USER';
const WATCH_PREDICT_COLUMN = 'WATCH_PREDICT_COLUMN';
 export{
     WATCH_GET_EXPENSE_DATA,
     WATCH_UPLOAD_STATEMENT,
     WATCH_LOGIN_USER,
     WATCH_PREDICT_COLUMN
 }