const GET_EXPENSE_DATA_STATE = 'GET_EXPENSE_DATA';
const GET_DAILY_DATA = 'GET_DAILY_DATA';
const SET_LOADING_STATE = 'SET_LOADING_STATE'

export {
    GET_EXPENSE_DATA_STATE,
    GET_DAILY_DATA,
    SET_LOADING_STATE
}