const GET_EXPENSE_DATA_STATE = 'GET_EXPENSE_DATA';
const GET_DAILY_DATA = 'GET_DAILY_DATA';
const SET_LOADING_STATE = 'SET_LOADING_STATE';
const UNSET_LOADING_STATE = 'UNSET_LOADING_STATE';
const SET_AUTH_STATE = 'SET_AUTH_STATE';
const SET_TEMPLATE_PATTERN_STATE = 'SET_TEMPLATE_PATTERN_STATE';
const SET_USER_LOGOUT = "SET_USER_LOGOUT";

export {
    GET_EXPENSE_DATA_STATE,
    GET_DAILY_DATA,
    SET_LOADING_STATE,
    SET_AUTH_STATE,
    SET_TEMPLATE_PATTERN_STATE,
    UNSET_LOADING_STATE,
    SET_USER_LOGOUT
}